name: Release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    branches: [ master ]

jobs:
  main:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache choosenim
      uses: actions/cache@v1
      id: cache-choosenim
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-stable

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-stable

    - uses: jiro4989/setup-nim-action@v1

    - name: Install packages
      run: nimble install -Y

    - name: Create folder
      run: mkdir release

    - name: Build
      run: nim c -d:release --app:gui -o:release/VRCChanger.exe src/VRCChanger.nim -Y

    - name: Create zip
      uses: vimtor/action-zip@v1
      with:
        files: release/
        recursive: true
        dest: release.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/upload-release-asset@master
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release.zip
        asset_name: release.zip
        asset_content_type: application/gzip

